export const FETCH_LANDING_PENDING = "FETCH_LANDING_PENDING";
export const FETCH_LANDING_FAILURE = "FETCH_LANDING_FAILURE";
export const FETCH_LANDING_SUCCESS = "FETCH_LANDING_SUCCESS";

export default [
    FETCH_LANDING_PENDING,
    FETCH_LANDING_FAILURE,
    FETCH_LANDING_SUCCESS,
];
